### ISSUE TITLE
Como criar um projeto básico em Yii.

### ISSUE THREAD

**Issue by PauloHartwig** [PauloHartwig/Trabalho-ESII#1]
Pesquisar e estudar como se cria um projeto padrão em Yii.

**Comment by VitorHSR** [comment]
Para criar um projeto básico, é necessário ter instalado as dependências das tecnologias necessárias  (#2 ).

**Comment by VitorHSR** [comment]
Logo após ter configurado o framework, basta executar o seguinte comando para criação de um projeto básico Yii 2.0: `composer create-project --prefer-dist yiisoft/yii2-app-basic <nome do projeto>`

**Comment by VitorHSR** [comment]
Se for preciso, você pode criar um projeto avançado com o seguinte comando:
`composer create-project --prefer-dist yiisoft/yii2-app-advanced <nome do projeto>`
Esse comando cria os arquivos do back-end e do front-end.
