### ISSUE TITLE
Criar vídeo

### ISSUE THREAD

**Issue by VitorHSR** [PauloHartwig/Trabalho-ESII#5]
Criar um vídeo ensinando a instalar e configurar uma aplicação.

**Comment by VitorHSR** [comment]
Em processo de edição.

**Comment by VitorHSR** [comment]
Está sendo enviado para o youtube.

**Comment by PauloHartwig** [comment]
Link do vídeo: https://www.youtube.com/watch?v=fgSPvnYs4pA&t=
