### ISSUE TITLE
Criar a Wiki

### ISSUE THREAD

**Issue by VitorHSR** [PauloHartwig/Trabalho-ESII#7]
Criar a wiki contendo o relatório de instalação do framework, o seu objetivo e o porquê de sua criação, a popularidade, os requisitos básicos para utiliza-lo, onde encontrar sua documentação, passos de instalação do framework, vantagens e desvantagens. e concluindo, o comparativo com framework já utilizados.

**Comment by PauloHartwig** [comment]
Feito!
Quer dizer mais ou menos.
Ainda falta algumas coisas pra ficar 10/10.
